### ISSUE TITLE
Problema con descargar las capas raster de batimetría

### ISSUE THREAD

**Issue by KyotoScarlette** [federicogazaba/introduccion-a-los-sig-con-qgis#1]
Hola Federico,
recientemente estaba practicando con el material pero encontré un error, en la pág. 19 en el cap. 2.7 aparece en descargar datos _vectorial y raster_ un link para abrir y descargar los ZIP. El de vectorial se descarga sin problema, pero el archivo Ráster manda a "WordPress > error  There has been a critical error on your website."

Intenté buscar en Natural Earth la carpeta Ráster, pero al ser una página nueva para mi se me dificulta entender dónde buscarla o qué descargar exactamente. Agradezco tu lectura y atención.

Gracias por el material!

Samantha Scarlette

**Comment by KyotoScarlette** [comment]
Descargué el ZIP de "Cross Blended Hypso with Relief, Water, Drains, and Ocean Bottom" parece ser similar o el mismo, el documento .TIF se llama diferente "HYP_LR_SR_OB_DR"

**Comment by federicogazaba** [comment]
Hola! El enlace correcto es éste:
https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/raster/NE1_HR_LC_SR_W_DR.zip
Correspondiente a "Natural Earth I with Shaded Relief, Water, and Drainages"

De igual forma, cualquiera de los ráster de esa página sirve para aprender
a trabajar con ráster.
Saludos y gracias nuevamente por tomarte el tiempo!

**Comment by KyotoScarlette** [comment]
Muchas gracias por el enlace!
